default_border none
default_floating_border none
hide_edge_borders --i3 both

for_window [app_id="gamescope"] border none, fullscreen enable
for_window [class="gamescope"] border none, fullscreen enable
for_window [app_id=".*"] border none
for_window [class=".*"] border none

output HEADLESS-1 mode 1920x1080@60Hz
exec swaymsg "output * adaptive_sync off"
